
package view;

import database.KetNoiDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import utils.QuanLyPhien;
/**
 *
 * @author lebao
 */
public class FrmDangNhap extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmDangNhap.class.getName());

    /**
     * Creates new form FrmDangNhap
     */
    public FrmDangNhap() {
        initComponents();
        setLocationRelativeTo(null);
        customUI();
        txtMatKhau.setEchoChar('•'); // đẹp & chuẩn macOS
        
        // Bấm ENTER để Đăng nhập
        getRootPane().setDefaultButton(btnDangNhap);
        
    }
    
    private void customUI() {

        addFocusBorder(txtTenDangNhap);
        addFocusBorder(txtMatKhau);

        // Hover nút
        addHoverButton(
            btnDangNhap,
            new java.awt.Color(255, 255, 255),
            new java.awt.Color(153, 153, 255),
            new java.awt.Color(153, 153, 255),
            java.awt.Color.WHITE
        );

        addHoverButton(
            btnDangKy,
            new java.awt.Color(153, 153, 255),
            java.awt.Color.WHITE,
            java.awt.Color.WHITE,
            new java.awt.Color(153, 153, 255)
        );

        addHoverLabel(
            jLabel4,
            new java.awt.Color(153, 153, 255),
            new java.awt.Color(98, 0, 238)
        );
    }
    
    // padding và khi bấm vô textfield sẽ hiện màu viền đậm hơn
    private void addFocusBorder(javax.swing.JTextField txt) {
        // padding cố định
        javax.swing.border.Border padding =
            javax.swing.BorderFactory.createEmptyBorder(0, 8, 0, 8);

        // viền thường
        javax.swing.border.Border normalBorder =
            javax.swing.BorderFactory.createLineBorder(
                new java.awt.Color(153, 153, 255), 2, true
            );

        // viền khi focus (tím đậm)
        javax.swing.border.Border focusBorder =
            javax.swing.BorderFactory.createLineBorder(
                new java.awt.Color(98, 0, 238), 2, true
            );

        // set border ban đầu (viền thường + padding)
        txt.setBorder(
            javax.swing.BorderFactory.createCompoundBorder(normalBorder, padding)
        );

        txt.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                txt.setBorder(
                    javax.swing.BorderFactory.createCompoundBorder(focusBorder, padding)
                );
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                txt.setBorder(
                    javax.swing.BorderFactory.createCompoundBorder(normalBorder, padding)
                );
            }
        });
    }

    
    private void addHoverButton(
        javax.swing.JButton btn,
        java.awt.Color bgNormal,
        java.awt.Color fgNormal,
        java.awt.Color bgHover,
        java.awt.Color fgHover
    ) {
        btn.setOpaque(true);
        btn.setBackground(bgNormal);
        btn.setForeground(fgNormal);
        btn.setFocusPainted(false);
        btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {
                btn.setBackground(bgHover);
                btn.setForeground(fgHover);
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                btn.setBackground(bgNormal);
                btn.setForeground(fgNormal);
            }
        });
    }
    
    private void addHoverLabel(
        javax.swing.JLabel lbl,
        java.awt.Color normalColor,
        java.awt.Color hoverColor
    ) {
        lbl.setForeground(normalColor);
        lbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        String text = lbl.getText();

        lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {
                lbl.setForeground(hoverColor);
                lbl.setText("<html><u>" + text + "</u></html>");
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                lbl.setForeground(normalColor);
                lbl.setText(text);
            }
        });
    }
    




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_DangNhap = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnDangKy = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtTenDangNhap = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JPasswordField();
        chkHienMatKhau = new javax.swing.JCheckBox();
        btnDangNhap = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));

        pn_DangNhap.setBackground(new java.awt.Color(255, 255, 255));
        pn_DangNhap.setPreferredSize(new java.awt.Dimension(350, 4));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CHÀO MỪNG ĐẾN VỚI TRANG ĐĂNG NHẬP ");

        btnDangKy.setBackground(new java.awt.Color(76, 175, 80));
        btnDangKy.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnDangKy.setForeground(new java.awt.Color(255, 255, 255));
        btnDangKy.setText("Đăng ký ngay");
        btnDangKy.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btnDangKy.setContentAreaFilled(false);
        btnDangKy.setName(""); // NOI18N
        btnDangKy.addActionListener(this::btnDangKyActionPerformed);

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Chưa có tài khoản? Đăng ký ngay nha");

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Quay lại rồi à? Mừng ghê ");

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("© 2026 Lê Nguyễn Thái Bảo – lenguyenthaib@gmail.com");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(75, 75, 75))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel9)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(btnDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel5)
                .addGap(52, 52, 52)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(44, 44, 44)
                .addComponent(btnDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txtTenDangNhap.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtTenDangNhap.setForeground(new java.awt.Color(153, 153, 255));
        txtTenDangNhap.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        txtTenDangNhap.setName(""); // NOI18N

        txtMatKhau.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtMatKhau.setForeground(new java.awt.Color(153, 153, 255));
        txtMatKhau.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));

        chkHienMatKhau.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        chkHienMatKhau.setForeground(new java.awt.Color(153, 153, 255));
        chkHienMatKhau.setText("Hiện mật khẩu");
        chkHienMatKhau.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        chkHienMatKhau.setContentAreaFilled(false);
        chkHienMatKhau.addActionListener(this::chkHienMatKhauActionPerformed);

        btnDangNhap.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(153, 153, 255));
        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        btnDangNhap.setContentAreaFilled(false);
        btnDangNhap.setName(""); // NOI18N
        btnDangNhap.addActionListener(this::btnDangNhapActionPerformed);

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 255));
        jLabel4.setText("Quên mật khẩu?");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(35, 166, 79));
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1.setText("ĐĂNG NHẬP");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 255));
        jLabel2.setText("Tài khoản");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 255));
        jLabel3.setText("Mật khẩu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chkHienMatKhau))
                        .addComponent(jLabel2)
                        .addComponent(txtTenDangNhap)
                        .addComponent(jLabel3)
                        .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(107, 107, 107)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1)
                .addGap(74, 74, 74)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(chkHienMatKhau))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );

        txtTenDangNhap.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout pn_DangNhapLayout = new javax.swing.GroupLayout(pn_DangNhap);
        pn_DangNhap.setLayout(pn_DangNhapLayout);
        pn_DangNhapLayout.setHorizontalGroup(
            pn_DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_DangNhapLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_DangNhapLayout.setVerticalGroup(
            pn_DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_DangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_DangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
    String sql = "SELECT nguoi_dung_id, ten_dang_nhap, vai_tro_id, trang_thai FROM nguoi_dung "
               + "WHERE ten_dang_nhap=? AND mat_khau=?";

    try (Connection conn = KetNoiDB.ketNoi();
         PreparedStatement ps = conn.prepareStatement(sql)) {

        ps.setString(1, txtTenDangNhap.getText());
        ps.setString(2, new String(txtMatKhau.getPassword()));

        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            int id = rs.getInt("nguoi_dung_id");
            String tenDangNhap = rs.getString("ten_dang_nhap");
            int vaiTro = rs.getInt("vai_tro_id");
            int trangThai = rs.getInt("trang_thai");

            // Nếu tài khoản bị khóa
            if (trangThai == 0) {
                JOptionPane.showMessageDialog(
                    this,
                    "Tài khoản đã bị khóa!",
                    "Thông báo",
                    JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            // Lưu thông tin phiên đăng nhập (bao gồm vai trò)
            String tenVaiTro = (vaiTro == 1) ? "ADMIN" : "USER";
            QuanLyPhien.datNguoiDungHienTai(id, tenDangNhap, tenVaiTro);

            // Tài khoản hoạt động
            if (vaiTro == 1) {
                new AdminForm().setVisible(true);
            } else {
                new UserForm().setVisible(true);
            }
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(
                this,
                "Sai tài khoản hoặc mật khẩu!",
                "Lỗi đăng nhập",
                JOptionPane.ERROR_MESSAGE
            );
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(
            this,
            "Lỗi kết nối CSDL!",
            "Lỗi",
            JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void chkHienMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkHienMatKhauActionPerformed
            if (chkHienMatKhau.isSelected()) {
        // Hiển thị mật khẩu dưới dạng văn bản thuần túy
                txtMatKhau.setEchoChar((char) 0);
            } else {
        // Ẩn mật khẩu với ký tự '•'
                txtMatKhau.setEchoChar('•');
    }
    }//GEN-LAST:event_chkHienMatKhauActionPerformed

    private void btnDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyActionPerformed
        new FrmDangKy().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDangKyActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        new FrmQuenMatKhau().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmDangNhap().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKy;
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JCheckBox chkHienMatKhau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pn_DangNhap;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTenDangNhap;
    // End of variables declaration//GEN-END:variables
}
