
package view;
import database.KetNoiDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author lebao
 */
public class FrmDangKy extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmDangKy.class.getName());

    /**
     * Creates new form FrmDangKy
     */
    public FrmDangKy() {
        initComponents();
        setLocationRelativeTo(null);
        customUI();
        txtMatKhau.setEchoChar('•'); // đẹp & chuẩn macOS
        txtXacNhanMatKhau.setEchoChar('•'); // đẹp & chuẩn macOS
        // Bấm ENTER để Đăng nhập
        getRootPane().setDefaultButton(btnDangKy);
    }

    private void customUI() {
        // ===== Focus + padding ô nhập =====
        addFocusBorder(txtTenDangNhap);
        addFocusBorder(txtHoTen);
        addFocusBorder(txtEmail);
        addFocusBorder(txtMatKhau);
        addFocusBorder(txtXacNhanMatKhau);
        
        // ===== Hover nút Đăng ký =====
        addHoverButton(
            btnDangKy,
            new java.awt.Color(255, 255, 255),   // nền thường
            new java.awt.Color(153, 153, 255),   // chữ thường
            new java.awt.Color(153, 153, 255),   // nền hover
            java.awt.Color.WHITE                // chữ hover
        );

        // ===== Hover nút Đăng nhập =====
        addHoverButton(
            btnDangNhap,
            new java.awt.Color(153, 153, 255),   // nền thường
            java.awt.Color.WHITE,                // chữ thường
            java.awt.Color.WHITE,                // nền hover
            new java.awt.Color(153, 153, 255)    // chữ hover
        );
    }

    private void addFocusBorder(javax.swing.JComponent txt) {

        // padding cố định
        javax.swing.border.Border padding =
            javax.swing.BorderFactory.createEmptyBorder(0, 8, 0, 8);

        // viền thường (tím nhạt)
        javax.swing.border.Border normalBorder =
            javax.swing.BorderFactory.createLineBorder(
                new java.awt.Color(153, 153, 255), 2, true
            );

        // viền focus (tím đậm)
        javax.swing.border.Border focusBorder =
            javax.swing.BorderFactory.createLineBorder(
                new java.awt.Color(98, 0, 238), 2, true
            );

        // border ban đầu
        txt.setBorder(
            javax.swing.BorderFactory.createCompoundBorder(normalBorder, padding)
        );

        txt.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                txt.setBorder(
                    javax.swing.BorderFactory.createCompoundBorder(focusBorder, padding)
                );
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                txt.setBorder(
                    javax.swing.BorderFactory.createCompoundBorder(normalBorder, padding)
                );
            }
        });
    }

    
    private void addHoverButton(
        javax.swing.JButton btn,
        java.awt.Color bgNormal,
        java.awt.Color fgNormal,
        java.awt.Color bgHover,
        java.awt.Color fgHover
    ) {
        btn.setOpaque(true);
        btn.setBackground(bgNormal);
        btn.setForeground(fgNormal);
        btn.setFocusPainted(false);
        btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {
                btn.setBackground(bgHover);
                btn.setForeground(fgHover);
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                btn.setBackground(bgNormal);
                btn.setForeground(fgNormal);
            }
        });
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTenDangNhap = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnDangKy = new javax.swing.JButton();
        chkHienMatKhau = new javax.swing.JCheckBox();
        txtXacNhanMatKhau = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblThongBao = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnDangNhap = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(35, 166, 79));
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1.setText("ĐĂNG KÝ TÀI KHOẢN");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 255));
        jLabel2.setText("Tên tài khoản");

        txtTenDangNhap.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtTenDangNhap.setForeground(new java.awt.Color(153, 153, 255));
        txtTenDangNhap.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 255));
        jLabel5.setText("Họ tên");

        txtHoTen.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtHoTen.setForeground(new java.awt.Color(153, 153, 255));
        txtHoTen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 255));
        jLabel6.setText("Email");

        txtEmail.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(153, 153, 255));
        txtEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));

        btnDangKy.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnDangKy.setForeground(new java.awt.Color(153, 153, 255));
        btnDangKy.setText("Đăng ký");
        btnDangKy.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        btnDangKy.setContentAreaFilled(false);
        btnDangKy.setName(""); // NOI18N
        btnDangKy.addActionListener(this::btnDangKyActionPerformed);

        chkHienMatKhau.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        chkHienMatKhau.setForeground(new java.awt.Color(153, 153, 255));
        chkHienMatKhau.setText("Hiện mật khẩu");
        chkHienMatKhau.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        chkHienMatKhau.setContentAreaFilled(false);
        chkHienMatKhau.addActionListener(this::chkHienMatKhauActionPerformed);

        txtXacNhanMatKhau.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtXacNhanMatKhau.setForeground(new java.awt.Color(153, 153, 255));
        txtXacNhanMatKhau.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 255));
        jLabel3.setText("Xác nhận mật khẩu");

        txtMatKhau.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtMatKhau.setForeground(new java.awt.Color(153, 153, 255));
        txtMatKhau.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 255));
        jLabel4.setText("Mật khẩu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chkHienMatKhau))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 32, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3)
                                        .addComponent(txtXacNhanMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(btnDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel1)
                .addGap(69, 69, 69)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtXacNhanMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(chkHienMatKhau))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(btnDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        lblThongBao.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblThongBao.setForeground(new java.awt.Color(255, 255, 255));
        lblThongBao.setText("CHÀO MỪNG ĐẾN VỚI TRANG ĐĂNG KÝ");

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Đăng ký nhanh gọn ko mất tiền mạng");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Có tài khoản rồi? Quay lại đăng nhập nhé");

        btnDangNhap.setBackground(new java.awt.Color(35, 166, 79));
        btnDangNhap.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnDangNhap.setText("Đăng Nhập");
        btnDangNhap.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btnDangNhap.setContentAreaFilled(false);
        btnDangNhap.setName(""); // NOI18N
        btnDangNhap.addActionListener(this::btnDangNhapActionPerformed);

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("© 2026 Lê Nguyễn Thái Bảo – lenguyenthaib@gmail.com ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblThongBao)
                            .addComponent(jLabel10))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel7)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(lblThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(44, 44, 44)
                .addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyActionPerformed
    String hoTen = txtHoTen.getText().trim();
    String tenDangNhap = txtTenDangNhap.getText().trim();
    String matKhau = new String(txtMatKhau.getPassword());
    String xacNhanMatKhau = new String(txtXacNhanMatKhau.getPassword());
    String email = txtEmail.getText().trim();
    int vaiTroId = 2; // Mặc định là người dùng

    // ===== KIỂM TRA DỮ LIỆU =====
    if (hoTen.isEmpty() || tenDangNhap.isEmpty() || matKhau.isEmpty() 
            || xacNhanMatKhau.isEmpty() || email.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Vui lòng điền đầy đủ thông tin!",
                "Lỗi",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!matKhau.equals(xacNhanMatKhau)) {
        JOptionPane.showMessageDialog(this,
                "Mật khẩu xác nhận không khớp!",
                "Lỗi",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (matKhau.length() < 6) {
        JOptionPane.showMessageDialog(this,
                "Mật khẩu phải ít nhất 6 ký tự!",
                "Lỗi",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Kiểm tra email đơn giản (regex cơ bản)
    if (!email.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
        JOptionPane.showMessageDialog(this,
                "Email không hợp lệ!",
                "Lỗi",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    // ===== KIỂM TRA TÊN ĐĂNG NHẬP / EMAIL TRÙNG =====
    String sqlCheck = "SELECT COUNT(*) FROM nguoi_dung WHERE ten_dang_nhap = ? OR email = ?";
    String sqlInsert = "INSERT INTO nguoi_dung (ten_dang_nhap, mat_khau, vai_tro_id, email, ho_ten) VALUES (?, ?, ?, ?, ?)";

    try (Connection conn = KetNoiDB.ketNoi();
         PreparedStatement psCheck = conn.prepareStatement(sqlCheck);
         PreparedStatement psInsert = conn.prepareStatement(sqlInsert)) {

        psCheck.setString(1, tenDangNhap);
        psCheck.setString(2, email);
        ResultSet rs = psCheck.executeQuery();
        if (rs.next() && rs.getInt(1) > 0) {
            JOptionPane.showMessageDialog(this,
                    "Tên đăng nhập hoặc email đã tồn tại!",
                    "Lỗi",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // ===== THÊM NGƯỜI DÙNG VÀO DB =====
        psInsert.setString(1, tenDangNhap);
        psInsert.setString(2, matKhau);
        psInsert.setInt(3, vaiTroId);
        psInsert.setString(4, email);
        psInsert.setString(5, hoTen);
        psInsert.executeUpdate();

        JOptionPane.showMessageDialog(this,
                "Đăng ký thành công!",
                "Thành công",
                JOptionPane.INFORMATION_MESSAGE);

        // Chuyển về form đăng nhập
        new FrmDangNhap().setVisible(true);
        this.dispose();

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this,
                "Lỗi đăng ký: " + e.getMessage(),
                "Lỗi",
                JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnDangKyActionPerformed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // Quay về form đăng nhập
        new FrmDangNhap().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void chkHienMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkHienMatKhauActionPerformed
        if (chkHienMatKhau.isSelected()) {
            txtMatKhau.setEchoChar((char) 0);  // Hiển thị
            txtXacNhanMatKhau.setEchoChar((char) 0);
        } else {
            txtMatKhau.setEchoChar('•');  // Ẩn
            txtXacNhanMatKhau.setEchoChar('•');
        }
    }//GEN-LAST:event_chkHienMatKhauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmDangKy().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKy;
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JCheckBox chkHienMatKhau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblThongBao;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTenDangNhap;
    private javax.swing.JPasswordField txtXacNhanMatKhau;
    // End of variables declaration//GEN-END:variables
}
