
package view;

import dao.BoCauHoiDAO;
import dao.CapHocDAO;
import dao.MonHocDAO;
import dao.NguoiDungDAO;
import model.BoCauHoi;
import model.CapHoc;
import model.MonHoc;
import model.NguoiDung;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import dao.CauHoiDAO;
import dao.DapAnDAO;
/**
 *
 * @author lebao
 */
public class FrmQuanLyBoCauHoi extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmQuanLyBoCauHoi.class.getName());
    private BoCauHoiDAO boCauHoiDAO = new BoCauHoiDAO();
    private CapHocDAO capHocDAO = new CapHocDAO();
    private MonHocDAO monHocDAO = new MonHocDAO();
    private NguoiDungDAO nguoiDungDAO = new NguoiDungDAO();
    private DefaultTableModel model;
    private CauHoiDAO cauHoiDAO = new CauHoiDAO();
    private DapAnDAO dapAnDAO = new DapAnDAO();
    /**
     * Creates new form FrmQuanLyBoCauHoi
     */
    public FrmQuanLyBoCauHoi() {
        if (!utils.QuanLyPhien.daDangNhap() || !utils.QuanLyPhien.layVaiTro().equals("ADMIN")) {
            JOptionPane.showMessageDialog(null, "Bạn không có quyền truy cập!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        initComponents();
        setLocationRelativeTo(null);
        khoiTaoBang();
        taiDuLieu();
        taiComboBox();
        tblBoCauHoi.setDefaultEditor(Object.class, null); // ko cho chỉnh sửa ô trong bảng trực tiếp
    }
    
        private void khoiTaoBang() {
        model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"ID", "Tên bộ môn", "Mô tả", "Cấp học", "Môn học", "Người tạo", "Trạng thái", "Công khai", "Ngày tạo"});
        tblBoCauHoi.setModel(model);
    }

    private void taiDuLieu() {
        model.setRowCount(0);
        List<BoCauHoi> list = boCauHoiDAO.getAll();
        for (BoCauHoi b : list) {
            CapHoc capHoc = capHocDAO.getAll().stream().filter(c -> c.getCapHocId() == b.getCapHocId()).findFirst().orElse(null);
            MonHoc monHoc = monHocDAO.getAll().stream().filter(m -> m.getMonHocId() == b.getMonHocId()).findFirst().orElse(null);
            NguoiDung nguoiTao = nguoiDungDAO.getById(b.getNguoiTao());
            model.addRow(new Object[]{
                b.getBoCauHoiId(),
                b.getTenBoCauHoi(),
                b.getMoTa(),
                capHoc != null ? capHoc.getTenCapHoc() : "N/A",
                monHoc != null ? monHoc.getTenMonHoc() : "N/A",
                nguoiTao != null ? nguoiTao.getHoTen() : "N/A",
                b.getTrangThai(),
                b.isCongKhai() ? "Có" : "Không",
                b.getNgayTao()
            });
        }
    }

    private void taiComboBox() {
        cboCapHoc.removeAllItems();
        cboMonHoc.removeAllItems();
        for (CapHoc c : capHocDAO.getAll()) {
            cboCapHoc.addItem(c);
        }
        for (MonHoc m : monHocDAO.getAll()) {
            cboMonHoc.addItem(m);
        }
    }

    private void lamMoi() {
        txtTenBo.setText("");
        txtMoTa.setText("");
        // Kiểm tra trước khi set index để tránh lỗi
        if (cboCapHoc.getItemCount() > 0) {
            cboCapHoc.setSelectedIndex(0);
        }
        if (cboMonHoc.getItemCount() > 0) {
            cboMonHoc.setSelectedIndex(0);
        }
        chkCongKhai.setSelected(false);
        tblBoCauHoi.clearSelection();
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTenBo = new javax.swing.JTextField();
        txtMoTa = new javax.swing.JTextField();
        cboCapHoc = new javax.swing.JComboBox<>();
        cboMonHoc = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        chkCongKhai = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnDuyet = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBoCauHoi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("Tên bộ câu hỏi");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setText("Mô tả");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setText("Chọn cấp học");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setText("Chọn môn học");

        chkCongKhai.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        chkCongKhai.setText("Công khai");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel5.setText("QUẢN LÝ BỘ CÂU HỎI");

        btnThem.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(this::btnThemActionPerformed);

        btnSua.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnSua.setText("Cập nhật");
        btnSua.addActionListener(this::btnSuaActionPerformed);

        btnXoa.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnXoa.setText("Xoá bỏ");
        btnXoa.addActionListener(this::btnXoaActionPerformed);

        btnDuyet.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnDuyet.setText("Duyệt");
        btnDuyet.addActionListener(this::btnDuyetActionPerformed);

        btnLamMoi.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(this::btnLamMoiActionPerformed);

        btnThoat.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnThoat.setText("Về trang chủ");
        btnThoat.addActionListener(this::btnThoatActionPerformed);

        tblBoCauHoi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tên bộ câu hỏi", "Mô Tả", "Cấp học", "Môn học", "Người tạo", "Trạng thái", "Công khai", "Ngày tạo"
            }
        ));
        tblBoCauHoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBoCauHoiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBoCauHoi);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThoat))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chkCongKhai))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenBo)
                                    .addComponent(txtMoTa)
                                    .addComponent(cboCapHoc, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboMonHoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(btnDuyet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                            .addComponent(btnThem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel2))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(469, 469, 469))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel5)
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTenBo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboCapHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(cboMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkCongKhai)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(btnSua)
                            .addComponent(btnXoa))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDuyet)
                            .addComponent(btnLamMoi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(76, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        String ten = txtTenBo.getText().trim();
        String moTa = txtMoTa.getText().trim();
        if (ten.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên bộ câu hỏi!");
            return;
        }
        BoCauHoi b = new BoCauHoi();
        b.setTenBoCauHoi(ten);
        b.setMoTa(moTa);
        b.setCapHocId(((CapHoc) cboCapHoc.getSelectedItem()).getCapHocId());
        b.setMonHocId(((MonHoc) cboMonHoc.getSelectedItem()).getMonHocId());
        b.setNguoiTao(utils.QuanLyPhien.layIdNguoiDungHienTai());
        b.setCongKhai(chkCongKhai.isSelected());
        if (boCauHoiDAO.insert(b)) {
            JOptionPane.showMessageDialog(this, "Thêm thành công!");
            taiDuLieu();
            lamMoi();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm thất bại!");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int row = tblBoCauHoi.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn bộ câu hỏi!");
            return;
        }
        int id = (int) model.getValueAt(row, 0);
        BoCauHoi b = boCauHoiDAO.getById(id);
        if (b != null) {
            b.setTenBoCauHoi(txtTenBo.getText().trim());
            b.setMoTa(txtMoTa.getText().trim());
            b.setCapHocId(((CapHoc) cboCapHoc.getSelectedItem()).getCapHocId());
            b.setMonHocId(((MonHoc) cboMonHoc.getSelectedItem()).getMonHocId());
            b.setCongKhai(chkCongKhai.isSelected());
            if (boCauHoiDAO.update(b)) {
                JOptionPane.showMessageDialog(this, "Sửa thành công!");
                taiDuLieu();
            } else {
                JOptionPane.showMessageDialog(this, "Sửa thất bại!");
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
    int row = tblBoCauHoi.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn bộ câu hỏi!");
        return;
    }
    int id = (int) model.getValueAt(row, 0);
    BoCauHoi bo = boCauHoiDAO.getById(id);
    if (bo == null) {
        JOptionPane.showMessageDialog(this, "Không tìm thấy bộ câu hỏi!");
        return;
    }
    if (JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa bộ câu hỏi và tất cả dữ liệu liên quan?") == JOptionPane.YES_OPTION) {
        // Xóa cascade: DapAn -> CauHoi -> BoCauHoi -> MonHoc (nếu không dùng chung)
        List<model.CauHoi> cauHois = cauHoiDAO.getByBoCauHoiId(id);
        for (model.CauHoi ch : cauHois) {
            List<model.DapAn> dapAns = dapAnDAO.getByCauHoiId(ch.getCauHoiId());
            for (model.DapAn da : dapAns) {
                dapAnDAO.delete(da.getDapAnId());
            }
            cauHoiDAO.delete(ch.getCauHoiId());
        }
        
        if (boCauHoiDAO.delete(id)) {
            int count = boCauHoiDAO.countByMonHocId(bo.getMonHocId());
            if (count == 0) {
                monHocDAO.delete(bo.getMonHocId());
            }
            JOptionPane.showMessageDialog(this, "Xóa thành công!");
            taiDuLieu();
            lamMoi();
        } else {
            JOptionPane.showMessageDialog(this, "Xóa thất bại!");
        }
    }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnDuyetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuyetActionPerformed
       int row = tblBoCauHoi.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn bộ câu hỏi!");
            return;
        }
        int id = (int) model.getValueAt(row, 0);
        BoCauHoi b = boCauHoiDAO.getById(id);
        if (b != null) {
            b.setTrangThai(b.getTrangThai().equals("CHO_DUYET") ? "DA_DUYET" : "CHO_DUYET");
            if (boCauHoiDAO.update(b)) {
                JOptionPane.showMessageDialog(this, "Duyệt thành công!");
                taiDuLieu();
            } else {
                JOptionPane.showMessageDialog(this, "Duyệt thất bại!");
            }
        }
    }//GEN-LAST:event_btnDuyetActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        lamMoi();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        new AdminForm().setVisible(true);
        setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void tblBoCauHoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBoCauHoiMouseClicked
    int row = tblBoCauHoi.getSelectedRow();
    if (row != -1) {
        txtTenBo.setText((String) model.getValueAt(row, 1));
        txtMoTa.setText((String) model.getValueAt(row, 2));
        
        // Set selected item cho combo box dựa trên tên
        String tenCapHoc = (String) model.getValueAt(row, 3);
        for (int i = 0; i < cboCapHoc.getItemCount(); i++) {
            if (cboCapHoc.getItemAt(i).getTenCapHoc().equals(tenCapHoc)) {
                cboCapHoc.setSelectedIndex(i);
                break;
            }
        }
        
        String tenMonHoc = (String) model.getValueAt(row, 4);
        for (int i = 0; i < cboMonHoc.getItemCount(); i++) {
            if (cboMonHoc.getItemAt(i).getTenMonHoc().equals(tenMonHoc)) {
                cboMonHoc.setSelectedIndex(i);
                break;
            }
        }
        
        chkCongKhai.setSelected("Có".equals(model.getValueAt(row, 7)));
    }
    }//GEN-LAST:event_tblBoCauHoiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmQuanLyBoCauHoi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDuyet;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<CapHoc> cboCapHoc;
    private javax.swing.JComboBox<MonHoc> cboMonHoc;
    private javax.swing.JCheckBox chkCongKhai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblBoCauHoi;
    private javax.swing.JTextField txtMoTa;
    private javax.swing.JTextField txtTenBo;
    // End of variables declaration//GEN-END:variables
}
