package view;

import dao.BaiThiDAO;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utils.QuanLyPhien;

/**
 * Giao diện xem lịch sử thi được thiết kế để tương thích với NetBeans GUI
 * Builder.
 */
public class pnlXemLichSuThi extends javax.swing.JPanel {

    private final BaiThiDAO baiThiDAO = new BaiThiDAO();
    private final SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
    private DefaultTableModel model;

    /**
     * Creates new form pnlXemLichSuThi
     */
    public pnlXemLichSuThi() {
        initComponents();
        khoiTaoThem();
        taiDuLieu();
    }

    private void khoiTaoThem() {
        model = (DefaultTableModel) tblLichSuThi.getModel();
        tblLichSuThi.setDefaultEditor(Object.class, null);
    }

    public void taiDuLieu() {
        int nguoiDungId = QuanLyPhien.layIdNguoiDungHienTai();
        if (nguoiDungId <= 0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa đăng nhập.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        model.setRowCount(0);
        List<Object[]> rows = baiThiDAO.getLichSuTheoNguoiDung(nguoiDungId);
        for (Object[] row : rows) {
            model.addRow(new Object[] {
                    row[0],
                    row[1],
                    row[2],
                    row[3],
                    row[4],
                    row[5],
                    row[6],
                    formatDateTime(row[7]),
                    formatDateTime(row[8]),
                    formatDuration(row[9]),
                    row[10] // cong_khai (ẩn hoặc dùng để check)
            });
        }
    }

    private String formatDateTime(Object value) {
        if (value == null) {
            return "";
        }
        if (value instanceof java.util.Date) {
            return dateFormat.format((java.util.Date) value);
        }
        return value.toString();
    }

    private String formatDuration(Object secondsObj) {
        if (secondsObj == null) {
            return "";
        }
        long seconds = ((Number) secondsObj).longValue();
        long minutes = seconds / 60;
        long remainSeconds = seconds % 60;
        return minutes + " phút " + remainSeconds + " giây";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTop = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlBtn = new javax.swing.JPanel();
        btnTaiLai = new javax.swing.JButton();
        btnXemChiTiet = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLichSuThi = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        setLayout(new java.awt.BorderLayout(12, 12));

        pnlTop.setOpaque(false);
        pnlTop.setLayout(new java.awt.BorderLayout());

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblTitle.setText("LỊCH SỬ KẾT QUẢ THI");
        pnlTop.add(lblTitle, java.awt.BorderLayout.WEST);

        pnlBtn.setOpaque(false);
        pnlBtn.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 0));

        btnTaiLai.setText("Tải lại");
        btnTaiLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaiLaiActionPerformed(evt);
            }
        });

        btnXemChiTiet.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        btnXemChiTiet.setText("Xem chi tiết");
        btnXemChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemChiTietActionPerformed(evt);
            }
        });
        pnlBtn.add(btnXemChiTiet);
        pnlBtn.add(btnTaiLai);

        pnlTop.add(pnlBtn, java.awt.BorderLayout.EAST);

        add(pnlTop, java.awt.BorderLayout.NORTH);

        tblLichSuThi.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        tblLichSuThi.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Mã bài thi", "Bộ câu hỏi", "Môn học", "Cấp học", "Tổng câu", "Đúng", "Điểm", "Bắt đầu",
                        "Kết thúc", "Thời lượng", "cong_khai"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        tblLichSuThi.setRowHeight(28);
        tblLichSuThi.getTableHeader().setReorderingAllowed(false);
        // Ẩn cột cong_khai
        tblLichSuThi.getColumnModel().getColumn(10).setMinWidth(0);
        tblLichSuThi.getColumnModel().getColumn(10).setMaxWidth(0);
        tblLichSuThi.getColumnModel().getColumn(10).setPreferredWidth(0);

        jScrollPane1.setViewportView(tblLichSuThi);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaiLaiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:initComponents
        taiDuLieu();
    }// GEN-LAST:initComponents

    private void btnXemChiTietActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnXemChiTietActionPerformed
        int selectedRow = tblLichSuThi.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một bài thi để xem chi tiết.", "Thông báo",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Lấy thông tin từ model (cột cong_khai ở vị trí 10)
        boolean isCongKhai = (boolean) model.getValueAt(selectedRow, 10);
        if (!isCongKhai) {
            JOptionPane.showMessageDialog(this, "Bộ câu hỏi này không được công khai đáp án.", "Thông báo",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        int baiThiId = (int) model.getValueAt(selectedRow, 0);
        String tenBoCauHoi = (String) model.getValueAt(selectedRow, 1);

        FrmXemChiTietBaiThi frm = new FrmXemChiTietBaiThi(baiThiId, tenBoCauHoi);
        frm.setVisible(true);
    }// GEN-LAST:event_btnXemChiTietActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:initComponents
    private javax.swing.JButton btnTaiLai;
    private javax.swing.JButton btnXemChiTiet;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlBtn;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JTable tblLichSuThi;
    // End of variables declaration//GEN-END:initComponents
}
