
package view;

import utils.QuanLyPhien;

/**
 *
 * @author lebao
 */
public class UserForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserForm.class.getName());
    private javax.swing.JMenuItem activeMenuItem;
    private pnlTaiLenBoCauHoi pnlTaiLenBoCauHoiView;
    private pnlXemLichSuThi pnlXemLichSuThiView;
    private pnlXemBangXepHang pnlXemBangXepHangView;

    private static final java.awt.Color MENU_DEFAULT_BG = new java.awt.Color(245, 245, 255);
    private static final java.awt.Color MENU_HOVER_BG = new java.awt.Color(230, 230, 255);
    private static final java.awt.Color MENU_ACTIVE_BG = new java.awt.Color(153, 153, 255);
    private static final java.awt.Color MENU_DEFAULT_FG = new java.awt.Color(80, 80, 80);

    /**
     * Creates new form UserForm
     */
    public UserForm() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        pnlMain.setLayout(new java.awt.CardLayout());

        pnlTaiLenBoCauHoiView = new pnlTaiLenBoCauHoi();
        pnlXemLichSuThiView = new pnlXemLichSuThi();
        pnlXemBangXepHangView = new pnlXemBangXepHang();

        pnlMain.add(pnlTaiLenBoCauHoiView, "TAI_LEN");
        pnlMain.add(pnlXemLichSuThiView, "LICH_SU");
        pnlMain.add(pnlXemBangXepHangView, "BANG_XEP_HANG");

        customMenuItem(btnTaiLenBoCauHoi);
        customMenuItem(btnLichSu);
        customMenuItem(btnXemBangXepHang);

        addMenuEffect(btnTaiLenBoCauHoi, "TAI_LEN");
        addMenuEffect(btnLichSu, "LICH_SU");
        addMenuEffect(btnXemBangXepHang, "BANG_XEP_HANG");

        btnCauHoiYeuThich.addActionListener(e -> {
            new FrmCauHoiYeuThich().setVisible(true);
        });

        // Mặc định chọn Lịch sử thi
        setActiveMenu(btnLichSu);
        refreshCardData("LICH_SU");
        ((java.awt.CardLayout) pnlMain.getLayout()).show(pnlMain, "LICH_SU");
    }

    private void customMenuItem(javax.swing.JMenuItem item) {
        item.setOpaque(true);
        item.setBackground(MENU_DEFAULT_BG);
        item.setForeground(MENU_DEFAULT_FG);
    }

    private void addMenuEffect(javax.swing.JMenuItem item, String cardName) {
        item.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {
                if (item != activeMenuItem) {
                    item.setBackground(MENU_HOVER_BG);
                }
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                if (item != activeMenuItem) {
                    item.setBackground(MENU_DEFAULT_BG);
                }
            }
        });

        item.addActionListener(e -> {
            setActiveMenu(item);
            refreshCardData(cardName);
            java.awt.CardLayout cl = (java.awt.CardLayout) pnlMain.getLayout();
            cl.show(pnlMain, cardName);
        });
    }

    private void refreshCardData(String cardName) {
        switch (cardName) {
            case "LICH_SU":
                if (pnlXemLichSuThiView != null) {
                    pnlXemLichSuThiView.taiDuLieu();
                }
                break;
            case "BANG_XEP_HANG":
                if (pnlXemBangXepHangView != null) {
                    pnlXemBangXepHangView.loadData();
                }
                break;
            default:
                break;
        }
    }

    private void setActiveMenu(javax.swing.JMenuItem item) {
        if (activeMenuItem != null) {
            activeMenuItem.setBackground(MENU_DEFAULT_BG);
            activeMenuItem.setForeground(MENU_DEFAULT_FG);
        }
        activeMenuItem = item;
        item.setBackground(MENU_ACTIVE_BG);
        item.setForeground(java.awt.Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnThiTracNghiem = new javax.swing.JMenu();
        btnChonDeThi = new javax.swing.JMenuItem();
        btnCauHoiYeuThich = new javax.swing.JMenuItem();
        btnXemXepHang = new javax.swing.JMenu();
        btnLichSu = new javax.swing.JMenuItem();
        btnXemBangXepHang = new javax.swing.JMenuItem();
        btnHeThong = new javax.swing.JMenu();
        btnCapNhatThongTin = new javax.swing.JMenuItem();
        btnTaiLenBoCauHoi = new javax.swing.JMenuItem();
        btnDangXuat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
                pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1508, Short.MAX_VALUE));
        pnlMainLayout.setVerticalGroup(
                pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1038, Short.MAX_VALUE));

        btnThiTracNghiem.setText("Thi trắc nghiệm");
        btnThiTracNghiem.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        btnChonDeThi.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnChonDeThi.setText("Chọn đề thi");
        btnChonDeThi.addActionListener(this::btnChonDeThiActionPerformed);
        btnThiTracNghiem.add(btnChonDeThi);

        btnCauHoiYeuThich.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnCauHoiYeuThich.setText("Câu hỏi yêu thích");
        btnThiTracNghiem.add(btnCauHoiYeuThich);

        jMenuBar1.add(btnThiTracNghiem);

        btnXemXepHang.setText("Tra cứu thông tin");
        btnXemXepHang.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        btnLichSu.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnLichSu.setText("Lịch sử kết quả");
        btnXemXepHang.add(btnLichSu);

        btnXemBangXepHang.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnXemBangXepHang.setText("Xem bảng xếp hạng");
        btnXemXepHang.add(btnXemBangXepHang);

        jMenuBar1.add(btnXemXepHang);

        btnHeThong.setText("Hệ thống");
        btnHeThong.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        btnCapNhatThongTin.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnCapNhatThongTin.setText("Cập nhật thông tin");
        btnCapNhatThongTin.addActionListener(this::btnCapNhatThongTinActionPerformed);
        btnHeThong.add(btnCapNhatThongTin);

        btnTaiLenBoCauHoi.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnTaiLenBoCauHoi.setText("Tải lên bộ câu hỏi");
        btnTaiLenBoCauHoi.addActionListener(this::btnTaiLenBoCauHoiActionPerformed);
        btnHeThong.add(btnTaiLenBoCauHoi);

        btnDangXuat.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.addActionListener(this::btnDangXuatActionPerformed);
        btnHeThong.add(btnDangXuat);

        jMenuBar1.add(btnHeThong);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDangXuatActionPerformed
        QuanLyPhien.dangXuat();
        new FrmDangNhap().setVisible(true);
        this.dispose();
        setLocationRelativeTo(null);
    }// GEN-LAST:event_btnDangXuatActionPerformed

    private void btnCapNhatThongTinActionPerformed(java.awt.event.ActionEvent evt) {
        new FrmCapNhatThongTin().setVisible(true);
        setLocationRelativeTo(null);
    }

    private void btnTaiLenBoCauHoiActionPerformed(java.awt.event.ActionEvent evt) {
        // Handled by card layout effect
    }

    private void btnChonDeThiActionPerformed(java.awt.event.ActionEvent evt) {
        new FrmLamBaiThi().setVisible(true);
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnCapNhatThongTin;
    private javax.swing.JMenuItem btnCauHoiYeuThich;
    private javax.swing.JMenuItem btnChonDeThi;
    private javax.swing.JMenuItem btnDangXuat;
    private javax.swing.JMenu btnHeThong;
    private javax.swing.JMenuItem btnLichSu;
    private javax.swing.JMenuItem btnTaiLenBoCauHoi;
    private javax.swing.JMenu btnThiTracNghiem;
    private javax.swing.JMenuItem btnXemBangXepHang;
    private javax.swing.JMenu btnXemXepHang;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
